name: L2 contracts ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  FOUNDRY_PROFILE: ci

jobs:
  build:
    defaults:
      run:
        working-directory: ./l2-contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1

      - name: Install Foundry
        uses: dutterbutter/foundry-zksync-toolchain@v1

      - name: Install dependencies
        run: forge install

      - name: Build contracts
        run: forge build --zksync

  test:
    defaults:
      run:
        working-directory: ./l2-contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1

      - name: Install Foundry
        uses: dutterbutter/foundry-zksync-toolchain@v1

      - name: Run forge tests
        run: |
          forge test --match-path "test/*.t.sol" --no-match-path "test/*.integration.t.sol" --zksync -vv

  lint:
    defaults:
      run:
        shell: bash
        working-directory: ./l2-contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1

      - name: Install Foundry
        uses: dutterbutter/foundry-zksync-toolchain@v1

      - name: Install dependencies
        run: forge install

      - name: Install scopelint
        uses: engineerd/configurator@v0.0.8
        with:
          name: scopelint
          repo: ScopeLift/scopelint
          fromGitHubReleases: true
          version: latest
          pathInArchive: scopelint-x86_64-linux/scopelint
          urlTemplate: https://github.com/ScopeLift/scopelint/releases/download/{{version}}/scopelint-x86_64-linux.tar.xz
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check formatting
        run: |
          scopelint --version
          scopelint check
